apiVersion: esctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: sentiment-Cluster
    region: us-east-2
    version: '1.17'

nodeGroups:
    - name: ng-worker
      instanceType: t2.small
      desiredCapacity: 2
      volumeSize: 4
      ssh:
        allow: True
        publicKeyName: linux-msi
        
