apiVersion: apps/v1
kind: Deployment

metadata:
    name: sentiment-app
    labels:
        app: sentiment-app

spec:
    replicas: 2
    selector:
        matchLabels:
            app: sentiment-app
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 50%
    template:
        metadata:
            labels:
                app: sentiment-app
            spec:
                containers:
                    - name: sentiment-app
                      image: 537672174807.dkr.ecr.us-east-2.amazonaws.com/sentiment:latest
                      ports: 
                        - containerPort: 8080


